import mockUsersData from '@/data/mockUsers.json';

export interface UserAddress {
    street: string;
    ward: string;
    district: string;
    city: string;
    country: string;
}

export interface User {
    _id?: string; // MongoDB _id (for API compatibility)
    id: string;
    user_name?: string; // For API compatibility
    username: string;
    email: string;
    password?: string;
    full_name?: string;
    phone_number?: string;
    avatar?: string;
    role: number; // 0: User, 1: Manager, 2: Admin
    type: 'WEBSITE' | 'GOOGLE';
    gender?: 'male' | 'female' | 'other' | '';
    address?: UserAddress;
    date_of_birth?: string;
    is_verified?: boolean;
    status: number; // 0: inactive, 1: active
    created_at: string;
    id_auth_provider?: string;
    accessToken?: string;
}

/**
 * Get all users
 * @returns Array of all users
 */
export const getAllUsers = (): User[] => {
    return mockUsersData.users as User[];
};

/**
 * Get user by ID
 * @param id - User ID
 * @returns User or undefined if not found
 */
export const getUserById = (id: string): User | undefined => {
    const users = getAllUsers();
    return users.find(user => user.id === id);
};

/**
 * Get user by username
 * @param username - Username
 * @returns User or undefined if not found
 */
export const getUserByUsername = (username: string): User | undefined => {
    const users = getAllUsers();
    return users.find(user => user.username === username);
};

/**
 * Get user by email
 * @param email - Email address
 * @returns User or undefined if not found
 */
export const getUserByEmail = (email: string): User | undefined => {
    const users = getAllUsers();
    return users.find(user => user.email.toLowerCase() === email.toLowerCase());
};

/**
 * Get user by username or email
 * @param usernameOrEmail - Username or email address
 * @returns User or undefined if not found
 */
export const getUserByUsernameOrEmail = (usernameOrEmail: string): User | undefined => {
    const users = getAllUsers();
    return users.find(
        user =>
            user.username.toLowerCase() === usernameOrEmail.toLowerCase() ||
            user.email.toLowerCase() === usernameOrEmail.toLowerCase()
    );
};

/**
 * Authenticate user (login)
 * @param usernameOrEmail - Username or email
 * @param password - Password
 * @returns User with accessToken or null if authentication fails
 */
export const authenticateUser = (usernameOrEmail: string, password: string): (User & { accessToken: string }) | null => {
    const user = getUserByUsernameOrEmail(usernameOrEmail);
    
    if (!user) {
        return null;
    }

    // For GOOGLE type users, no password check
    if (user.type === 'GOOGLE') {
        return null;
    }

    // Check password (in real app, this should compare hashed password)
    if (user.password !== password) {
        return null;
    }

    // Check if user is active
    if (user.status !== 1) {
        return null;
    }

    // Generate mock access token (in real app, this should be generated by backend)
    const accessToken = `mock_access_token_${user.id}_${Date.now()}`;

    // Return user without password, with API-compatible format
    const { password: _, ...userWithoutPassword } = user;
    return {
        ...userWithoutPassword,
        _id: user.id, // Add _id for API compatibility
        user_name: user.username, // Add user_name for API compatibility
        accessToken,
    } as User & { accessToken: string };
};

/**
 * Register new user
 * @param userData - User data for registration
 * @returns Created user or null if registration fails
 */
export const registerUser = (userData: {
    username: string;
    email: string;
    password: string;
    full_name?: string;
    phone_number?: string;
}): User | null => {
    const users = getAllUsers();

    // Check if username or email already exists
    const existingUser = users.find(
        user =>
            user.username.toLowerCase() === userData.username.toLowerCase() ||
            user.email.toLowerCase() === userData.email.toLowerCase()
    );

    if (existingUser) {
        return null; // User already exists
    }

    // Create new user
    const newUser: User = {
        id: String(users.length + 1),
        username: userData.username,
        email: userData.email,
        password: userData.password, // In real app, this should be hashed
        full_name: userData.full_name || '',
        phone_number: userData.phone_number || '',
        avatar: '/avatar/user-icon.webp',
        role: 0, // Default role: User
        type: 'WEBSITE',
        gender: '',
        address: {
            street: '',
            ward: '',
            district: '',
            city: '',
            country: '',
        },
        date_of_birth: '',
        is_verified: false,
        status: 1, // Active by default
        created_at: new Date().toISOString(),
    };

    return newUser;
};

/**
 * Update user information
 * @param userId - User ID
 * @param updates - Fields to update
 * @returns Updated user or null if not found
 */
export const updateUser = (
    userId: string,
    updates: Partial<Omit<User, 'id' | 'created_at' | 'password'>>
): User | null => {
    const user = getUserById(userId);
    
    if (!user) {
        return null;
    }

    // Return updated user (in real app, this would update the database)
    return {
        ...user,
        ...updates,
    };
};

/**
 * Get users by role
 * @param role - Role (0: User, 1: Manager, 2: Admin)
 * @returns Array of users with the specified role
 */
export const getUsersByRole = (role: number): User[] => {
    const users = getAllUsers();
    return users.filter(user => user.role === role);
};

/**
 * Get active users only
 * @returns Array of active users
 */
export const getActiveUsers = (): User[] => {
    const users = getAllUsers();
    return users.filter(user => user.status === 1);
};

/**
 * Get verified users only
 * @returns Array of verified users
 */
export const getVerifiedUsers = (): User[] => {
    const users = getAllUsers();
    return users.filter(user => user.is_verified === true);
};

/**
 * Search users by query (username, email, or full name)
 * @param query - Search query string
 * @param limit - Maximum number of results (default: 10)
 * @returns Array of matching users
 */
export const searchUsers = (query: string, limit: number = 10): User[] => {
    if (!query || query.trim().length === 0) {
        return [];
    }

    const users = getAllUsers();
    const lowerQuery = query.toLowerCase().trim();

    const results = users
        .filter(
            user =>
                user.username.toLowerCase().includes(lowerQuery) ||
                user.email.toLowerCase().includes(lowerQuery) ||
                (user.full_name && user.full_name.toLowerCase().includes(lowerQuery))
        )
        .slice(0, limit);

    return results;
};

/**
 * Validate user credentials
 * @param usernameOrEmail - Username or email
 * @param password - Password
 * @returns true if credentials are valid, false otherwise
 */
export const validateUserCredentials = (usernameOrEmail: string, password: string): boolean => {
    const user = getUserByUsernameOrEmail(usernameOrEmail);
    
    if (!user) {
        return false;
    }

    // For GOOGLE type users, no password check
    if (user.type === 'GOOGLE') {
        return false;
    }

    // Check password (in real app, this should compare hashed password)
    return user.password === password && user.status === 1;
};

/**
 * Check if username is available
 * @param username - Username to check
 * @returns true if available, false if already taken
 */
export const isUsernameAvailable = (username: string): boolean => {
    const user = getUserByUsername(username);
    return !user;
};

/**
 * Check if email is available
 * @param email - Email to check
 * @returns true if available, false if already taken
 */
export const isEmailAvailable = (email: string): boolean => {
    const user = getUserByEmail(email);
    return !user;
};

